name: Deploy Dev to GitHub Pages

on:
  push:
    branches:
      - dev # Скрипт срабатывает при пуше в ветку dev

permissions:
  contents: write # КРИТИЧЕСКИ ВАЖНО: Без этого экшен не сможет записать файлы в ветку gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      # ИСПРАВЛЕНО: Изменено название репозитория в --base-href на /tutor-app/dev/
      - name: Build Angular Dev
        run: npx ng build --configuration=development --base-href=/tutor-app/dev/

      # ИСПРАВЛЕНО: Изменено имя папки в dist на dist/tutor-app/browser
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/tutor-app/browser # Проверь локально: если в dist нет подпапки browser, оставь просто dist/tutor-app
          target-folder: dev 
          branch: gh-pages