name: Deploy Dev to GitHub Pages

on:
  push:
    branches:
      - dev

# Права на уровне всего воркфлоу
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build Angular Dev
        run: npx ng build --configuration=development --base-href=/tutor-app/dev/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/tutor-app/browser # Проверь локально: если в dist папка без /browser, оставь dist/tutor-app
          target-folder: dev
          branch: gh-pages